name 'opensirf_cookbook_register'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures opensirf_cookbook_register'
long_description 'Installs/Configures opensirf_cookbook_register'
version '0.1.0'
depends 'tomcat'
depends 'lvm'
